services:
  claude-dev:
    build: .
    container_name: claude-dukdb-dev
    volumes:
      # Mount the current directory
      - .:/workspace
      # Share the local ~/.claude directory
      - ${HOME}/.claude:/home/claude/.claude
      # Persist Nix store for faster rebuilds
      - nix-store:/nix
      # Persist Nix profile
      - claude-nix-profile:/home/claude/.nix-profile
    environment:
      # Claude Code environment variables
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # Git configuration
      - GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME:-Claude Developer}
      - GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL:-claude@example.com}
      - GIT_COMMITTER_NAME=${GIT_COMMITTER_NAME:-Claude Developer}
      - GIT_COMMITTER_EMAIL=${GIT_COMMITTER_EMAIL:-claude@example.com}
    working_dir: /workspace
    stdin_open: true
    tty: true
    network_mode: host

volumes:
  nix-store:
  claude-nix-profile: